--- #YAML:1.0
name:               Net-Dict
version:            2.08
abstract:           client API for accessing dictionary servers (RFC 2229)
author:
    - Neil Bowers <neil@bowers.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    IO::Socket:  0
    Net::Cmd:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
