---
abstract: 'client API for accessing dictionary servers (RFC 2229)'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Differences: '0.62'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Dict
no_index:
  directory:
    - t
    - inc
  package:
    - Net::Dict::TestConfig
requires:
  AppConfig::Std: '0'
  Carp: '0'
  IO::Socket: '0'
  Net::Cmd: '0'
  perl: '5.006'
resources:
  repository: https://github.com/neilbowers/Net-Dict
version: '2.18'
